### ISSUE TITLE
no magic added

### ISSUE THREAD

**Issue by Rogenar** [fzzyhmstrs/ai#102]
I can't add the undying enchantment to the armor. Is this a mistake or am I doing it wrong?
![ss1](https://github.com/fzzyhmstrs/ai/assets/122460325/466d0e6f-fbd0-44eb-806c-2b7c891f3d88)
versiyon amethyst_imbuement-1.20.1-03

**Comment by fzzyhmstrs** [comment]
Undying isn't an armor enchantment. It it added to the Totem of Amethyst only.

**Comment by Rogenar** [comment]
I understand. I have the spell descriptions mod and in the description it said it was added to the armor. I guess this explanation fooled me :D
