### ISSUE TITLE
Mod Amethyst Imbuement can't handle latest patchouli mod version

### ISSUE THREAD

**Issue by Cape-City** [fzzyhmstrs/ai#105]
It seems the Amethyst Imbuement mod checks exactly for the version Patchouli-1.19.4-79-FABRIC.jar and therefor cannot handle the version Patchouli-1.19.4-79.1-FABRIC.jar. Maybe it should for minimum version and higher.

**Comment by fzzyhmstrs** [comment]
It does do a greater-than-or-equal check:

`   "patchouli": ">=1.19.4-79-FABRIC",`

**Comment by Cape-City** [comment]
Seems not to be doing what it should:

![grafik](https://github.com/fzzyhmstrs/ai/assets/122229367/bffc0b5c-8339-4ca4-ae70-77416510c9b3)

**Comment by fzzyhmstrs** [comment]
This is really on patchouli for not using proper versioning conventions, but I'll try to play around with it to find a setting that works.

**Comment by Cape-City** [comment]
The new versions seems to recognize the latest patchouli release ;)

**Comment by fzzyhmstrs** [comment]
Correct, the latest version dodges this issue by simply requiring that patchouli be installed at all. There were no variations of a version check I could get working. Closing this.

**Comment by hatkidchan** [comment]
Happens with latest Patchouli too, I don't know who to blame, Fabric's version checks, Patchouli for inconsistent versioning or both
> `- Replace mod 'Patchouli' (patchouli) 1.20.1-84.1-FABRIC with version 1.20.1-81-FABRIC or later.`

- `amethyst_imbuement-1.20.1-19.8.jar`
- `Patchouli-1.20.1-84.1-FABRIC.jar`

Not creating a new issue because it's literally this exact one

Workaround: using Patchouli 84 instead of 84.1 seems to just work

**Comment by fzzyhmstrs** [comment]
This is an issue with how patchouli is versioned
