### ISSUE TITLE
The guide book has missing files in zh_cn language

### ISSUE THREAD

**Issue by Kengroo1024** [fzzyhmstrs/ai#106]
I tested in the latest version 1.20.1, mod's version 1.20.1-07, with no other mods loaded except fabric and some premods.

![image](https://github.com/fzzyhmstrs/ai/assets/134791690/a034097c-d026-4916-8e8f-33765e4cbd2e)

There is the log.

> Caused by: java.lang.RuntimeException: Category amethyst_imbuement:scepter_totem_augments specifies parent amethyst_imbuement:scepter_augments, but it could not be found
> 	at vazkii.patchouli.client.book.BookCategory.build(BookCategory.java:161) ~[%5B�������ֲ�%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$1(BookContentsBuilder.java:87) ~[%5B�������ֲ�%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
> 	... 29 more

**Comment by fzzyhmstrs** [comment]
I would need someone to help update the localization. I can't update zh_cn myself.

**Comment by Kengroo1024** [comment]
I think you should keep untranslated part in  English, not leaving a bug here.

I'm trying to complete the zh_cn.json in the folder \amethyst_imbuement-1.20.1-06.jar\assets\amethyst_imbuement\lang\. 

How can I give it to you? It seems like the file doesn't exist in this repo.

**Comment by Kengroo1024** [comment]
I'm trying to update the lang file, then I will push it to you

**Comment by soloopooo** [comment]
> I would need someone to help update the localization. I can't update zh_cn myself.

This is a solution on MCBBS:
![图片](https://github.com/fzzyhmstrs/ai/assets/36123081/4282fe44-4d2e-43d9-81df-12398fcee6dc)

Translate: 
Delete the `en_us` in `assets\amethyst_imbuement\patchouli_books\glistering_tome`, then rename the `zh_cn` to `en_us`

I think it's not the lang bug but the code bug.
