### ISSUE TITLE
1.19.2 index out of bounds?

### ISSUE THREAD

**Issue by netcore10** [fzzyhmstrs/ai#107]
https://paste.atlauncher.com/view/63a73bfd-ae52-408b-826a-6758630ffe69

![image](https://github.com/fzzyhmstrs/ai/assets/181536/9b3dc548-093b-44c2-be8e-c827664ae064)

**Comment by fzzyhmstrs** [comment]
Is there something in particular that led you to open this issue here? I'm seeing that the index error is caused by some "Railways" mod:
![image](https://github.com/fzzyhmstrs/ai/assets/72876796/760b82ee-a8aa-4907-b18f-f0d778a4ebae)

**Comment by netcore10** [comment]
the hammer, a spell, it all crashed to that error

**Comment by fzzyhmstrs** [comment]
ok, I don't crash when I use the Fzzyhammer's spell on 1.19.2, so it seems like the Railways mod or some other mod is causing an issue on use.

**Comment by netcore10** [comment]
this seems to happen server side, don't know if it's relevent.

**Comment by fzzyhmstrs** [comment]
Railways issue is closed, so marking this closed.
