### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Developer2704** [fzzyhmstrs/ai#109]
Can you add a config option to enable the lustrous scepter recipe?

**Comment by fzzyhmstrs** [comment]
This has been added in 1.20.1-11

In the config folder, there is a new `resources_v0` file. Inside is a list of disabled recipes. Inside are the recipe names for the iridescent and lustrous scepter. To enable them, remove those recipes from the list.

`"optional/iridescent_scepter_imbuing"`
`"optional/lustrous_scepter_imbuing"`
