### ISSUE TITLE
Grindstone Crash

### ISSUE THREAD

**Issue by Kuggle01** [fzzyhmstrs/ai#11]
You can use a grind stone on a scepter to remove all the spells, you can still cast the last selected spell after this but attempting to change spells after this will crash the game https://paste.ee/p/uOo5Q 
While I'm here, is there any other way to remove a spell from a scepter?

**Comment by fzzyhmstrs** [comment]
Thank you for the report; an interesting use case I didn't consider in development (removing all spells after crafting and then using the scepter before adding another). I'll look into a fix for that usage. The intended behavior is for the scepter to revert to magic missile and enchant itself with magic missile if it doesn't have any spells to select from.

For alternative scepter spell removal, the **Disenchanting Table** can remove specific undesired enchantments (from anything, not just scepters).

**Comment by fzzyhmstrs** [comment]
Latest versions resolve both issues related to grinding scepters. Scepters revert to their basic state and cast/enchant themselves with magic missile.
