### ISSUE TITLE
Tier 3 spells not targeting players or animals

### ISSUE THREAD

**Issue by Egg-Runner** [fzzyhmstrs/ai#119]
Some of the tier 3 spells ive tested wont work unless im targeting hostile mobs like zombies and skeletons. I cant target players, animals like chickens cows and wolves, or other passive mobs or just select an area of the ground to attack. The spells I've tested so far are, winters grasp, lightning storm and comet storm. The tier 1 and 2 spells seem to work as normal. Though ball lightning also does not target players, but will target passive mobs like cows and chickens.

**Comment by fzzyhmstrs** [comment]
By default most spells are not PVP enabled, except maybe if caught in an AOE like fireball. PVP mode for spells can be turned on individually or forced for all spells in the configs

**Comment by Egg-Runner** [comment]
I see, is it also config that forces some of these spells to have to target acceptable enemies? Or is it part of the mod that it cant just be cast on the area you aim it at?

thanks for the quick reply btw
