### ISSUE TITLE
[Feature Request] Add enchantment description support

### ISSUE THREAD

**Issue by Kuggle01** [fzzyhmstrs/ai#12]
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions Enchantment desricptions is a mod that adds descs to enchantments, it has a ton of support for other mods too. I know the enchantments in this mod are desribed in the tome, but it'd be nice either way

**Comment by fzzyhmstrs** [comment]
Excellent suggestion! I'm planning on adding descriptions to my lore books already; I'll work to add Enchantment Descriptions support in parallel.

**Comment by fzzyhmstrs** [comment]
Newest releases add Enchantment Description support, and also add the descriptions into the books of lore/mythos.
