### ISSUE TITLE
Unable to build up modifiers by imbuing in multiplayer servers

### ISSUE THREAD

**Issue by snowflakemilktea** [fzzyhmstrs/ai#120]
### Version
Minecraft 1.20.1, Fabric 0.14.22, Amethyst Imbuement 1.20.1-10

### Description
Modifiers don't change when imbuing in multiplayer servers.

https://github.com/fzzyhmstrs/ai/assets/145715286/71278176-c770-4cf8-a709-62013531498c

In this video, I am imbuing an [Enduring Scepter] into a [Bardic Scepter], however, the modifier of the [Bardic Scepter] doesn't change. The modifier of the [Bardic Scepter] should build up to **Enduring, Attuned** instead of staying at **Lesser Enduring**.

Imbuing in the singleplayer game is working as expected, getting an **Enduring, Attuned** Bardic Scepter.

### Installed Mods
amethyst_core-1.2.2+1.20.1
amethyst_imbuement-1.20.1-10
fabric-api-0.88.1+1.20.1
fabric-language-kotlin-1.10.10+kotlin.1.9.10
fzzy_core-0.2.7+1.20.1
Patchouli-1.20.1-81-FABRIC
trinkets-3.7.1

**Comment by fzzyhmstrs** [comment]
Hi, this issue should be resolved in Amethyst Core 1.3.0
