### ISSUE TITLE
Server Crash while using 'a_scepter_so_fowl'

### ISSUE THREAD

**Issue by suitun** [fzzyhmstrs/ai#124]
[crash-2023-10-30_20.40.33-server.txt](https://github.com/fzzyhmstrs/ai/files/13205268/crash-2023-10-30_20.40.33-server.txt)
java.lang.IllegalArgumentException: Duplicate id value for 21!

That's really a fowl scepter. The server can't start anymore.
I removed the chunk where this entity is located. 
But I'm afraid other players will still use this staff.
The mod Version is 10, has this issue been fixed in a higher version?

**Comment by fzzyhmstrs** [comment]
I'm checking on this. I can't replicate in my own dev instances, but I can in another server. 

In the meantime, you can disable the spell Torrent of Beaks in the config if you need to. Just open the `torrent_of_beaks_v0` config in the `spells` subfolder and set "enabled" to false
![image](https://github.com/fzzyhmstrs/ai/assets/72876796/e16d72d7-621c-4abf-b0f0-80c6c7feebb2)

**Comment by fzzyhmstrs** [comment]
Do you happen to have any mods that modify chickens, add new chickens, anything like that?

**Comment by fzzyhmstrs** [comment]
Seems related to Meadow

**Comment by suitun** [comment]
Yes, I installed Meadow.

https://www.curseforge.com/minecraft/mc-mods/beachparty
I think it could also related to this,？With the addition of a biological pelican, which lays eggs like chickens.

**Comment by fzzyhmstrs** [comment]
So far, we've found it to be Solely related to Meadow. The [Lets Do] team is working on a fix from their end, and Curseforge is currently reviewing a patch to Amethyst Imbuement that dodges the issue from my end. Already up on Modrinth as version 1.20.1-13. If the Pelican also causes issues, [Lets Do] will have to fix that mod too.

**Comment by fzzyhmstrs** [comment]
Curseforge finally approved. Issue should be resolved from at least one end now
