### ISSUE TITLE
Witch House Basement waterlogging

### ISSUE THREAD

**Issue by ZekeZDev** [fzzyhmstrs/ai#125]
![image](https://github.com/fzzyhmstrs/ai/assets/81902668/66055d6e-e82f-405a-9d09-95e3a8688936)
![image](https://github.com/fzzyhmstrs/ai/assets/81902668/be73cd1e-e578-4909-8f58-fa6c79e91184)

If the Witch house basement is created to be inside underground water it will remove water except for the parts that can get waterlogged (stairs, fences etc) this can happen quite a fair amount as the witch basement is a rather large structure.

**Comment by fzzyhmstrs** [comment]
I've tried a few things to mitigate this, but unfortunately MC code *really* wants blocks to be placed as waterlogged if the structure is underwater. I might try some other things at some point, or consider taking out some of the stairs

**Comment by ZekeZDev** [comment]
Yeah not sure on the whole process for it. "Illager Invasion" had a similar issue with waterlogging. Not sure how useful this is but this is their commit that fixed the issue: https://github.com/Fuzss/illagerinvasion/commit/42f04f2e66140d9a15da40afd558f8b09dc24415

I hope this can help, AI is a really great mod and been really fun to play with.

**Comment by fzzyhmstrs** [comment]
I've implemented a solution that follows Fuzs's strategy, so this should be fixed in the latest versions
