### ISSUE TITLE
[1.20.1] AssertionError Occurs Due to Unknown Entity Class 'BaseHamsterEntity' in amethyst imbuement Mod

### ISSUE THREAD

**Issue by windy664** [fzzyhmstrs/ai#130]
MohistMC/Banner/issues/180

[crash-2023-12-02_14.17.31-server.txt](https://github.com/fzzyhmstrs/ai/files/13533655/crash-2023-12-02_14.17.31-server.txt)
[crash-2023-12-02_13.33.15-server.txt](https://github.com/fzzyhmstrs/ai/files/13533656/crash-2023-12-02_13.33.15-server.txt)
[crash-2023-12-02_15.05.03-server.txt](https://github.com/fzzyhmstrs/ai/files/13533657/crash-2023-12-02_15.05.03-server.txt)

**Comment by windy664** [comment]
While using
![05900f620ae2c59d94922ac1ffe7056f](https://github.com/fzzyhmstrs/ai/assets/81475218/8c9af442-39b7-49a7-be5f-73f9f7c77548)

**Comment by fzzyhmstrs** [comment]
Closing due to fix and close-out on Banner end: https://github.com/MohistMC/Banner/issues/180
