### ISSUE TITLE
The built jars contains wrong file

### ISSUE THREAD

**Issue by SettingDust** [fzzyhmstrs/ai#133]
![图片](https://github.com/fzzyhmstrs/ai/assets/19922286/4cda24d4-50ff-42a8-91f6-77786e480e93)
![图片](https://github.com/fzzyhmstrs/ai/assets/19922286/8ccd13a8-44da-4a04-b692-989891de47b4)

**Comment by fzzyhmstrs** [comment]
What are you trying to show me here?

**Comment by SettingDust** [comment]
> What are you trying to show me here?

License and credits

**Comment by fzzyhmstrs** [comment]
fixed in latest versions
