### ISSUE TITLE
Enchanting description

### ISSUE THREAD

**Issue by LoudShriek** [fzzyhmstrs/ai#134]
Hi. Is there any way to see all the enchants while using imbuing table?
I saw there is a config called single enchant tooltip.

![image](https://github.com/fzzyhmstrs/ai/assets/86960480/aeee2b39-994b-47eb-89ab-70aef697589b)

Does that mean if i leave it like this i should see all the enchant possibilities in imbuing table?
Mine is looking like this.

![image](https://github.com/fzzyhmstrs/ai/assets/86960480/ae546f01-749e-40cb-8f5d-c7558da7bd7c)

**Comment by fzzyhmstrs** [comment]
Hi. Currently those values aren't used for anything internally. Sorry for any confusion. Currently there is no way to see every enchant that is going to be created by the table.

**Comment by LoudShriek** [comment]
Thanks
