### ISSUE TITLE
Ametrine Tools aren't displayed properly

### ISSUE THREAD

**Issue by SpaceReptile** [fzzyhmstrs/ai#135]
When they're in your hand, they don't show up like actual tools and just items instead. 
![default](https://github.com/fzzyhmstrs/ai/assets/25854100/d05f051c-23bb-477f-9c2a-5efedd09daaf)
![ametrine](https://github.com/fzzyhmstrs/ai/assets/25854100/bf0eb0b9-1318-4948-ad09-396e5ae1fef6)

**Comment by fzzyhmstrs** [comment]
What version of the mod is this? Is this a version from 1.19.2?
