### ISSUE TITLE
something ain't right i just installed a pack

### ISSUE THREAD

**Issue by Yeet1092** [fzzyhmstrs/ai#138]
![Screenshot (81)](https://github.com/fzzyhmstrs/ai/assets/160265545/21484f96-fac6-4d09-91dd-d6128357d57e)
[latest.log](https://github.com/fzzyhmstrs/ai/files/14313830/latest.log)

**Comment by Yeet1092** [comment]
it is version 1.19.2 forge (fabric does give out the same error)

**Comment by fzzyhmstrs** [comment]
This doesn't seem to have anything to do with me. I see immediatelyfast and crittersandcompanions in the log.

**Comment by Yeet1092** [comment]
[rei-issues.log](https://github.com/fzzyhmstrs/ai/files/14313896/rei-issues.log)
here is the fabric error

**Comment by fzzyhmstrs** [comment]
Empty log. and again, this doesn't seem to have anything to do with my mod Amethyst Imbuement

**Comment by Yeet1092** [comment]
deletead  immediatelyfast and crittersandcompanions 
[latest.log](https://github.com/fzzyhmstrs/ai/files/14313930/latest.log)
still crashing i canno't see anything releated to what is wrong if you could tell me what causes the crashes i would try to deleat those
