### ISSUE TITLE
Fall damage causes Sardonyx Elemental to spawn - is this intended?

### ISSUE THREAD

**Issue by drwhut** [fzzyhmstrs/ai#140]
Hey there! I've been playing around with this mod in a modpack that I'm making, and I noticed that the first time I take any kind of damage (whether it be fall damage, stepping into lava, etc.), the Sardonyx Elemental immediately spawns. However, when I look at the advancement, it says that the trigger was "hurt_by_elemental":

![hurt_by_elemental](https://github.com/fzzyhmstrs/ai/assets/13645454/96958e8f-eb36-412d-98bf-03537a51e579)

Is this the intended behaviour? The in-game guidebook does not mention how it spawns, and there is no info about it on the GitHub wiki or on [the community wiki](https://amethyst-imbuement.fandom.com).

For reference, I have also tested this mod on it's own with version 19.1, with Minecraft 1.20.1, and Fabric 0.15.7, with the same result.

**Comment by fzzyhmstrs** [comment]
Not intended, and version 19.2 will have a fix for it. For the record, its not spawning. You are getting an advancement that when working properly only is granted when you are hurt by the elemental itself
