### ISSUE TITLE
AI Armor is not trimmable

### ISSUE THREAD

**Issue by Rymka69** [fzzyhmstrs/ai#142]
Can't apply Armor Trims to any of the AI Armor (tried with all the sets currently in AI). Trying to just put the Armor into the Smithing Table slot for armor is not possible with or without any items in other slots.
![image](https://github.com/fzzyhmstrs/ai/assets/91845700/957e5d01-334d-4385-be34-5cdd799cd1f2)

Tried with just these mods:
amethyst_core-1.4.9+1.20.1.jar
amethyst_imbuement-1.20.1-19.2.jar
fabric-api-0.91.0+1.20.1.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
fzzy_core-0.5.0+1.20.1.jar
Patchouli-1.20.1-84-FABRIC.jar
trinkets-3.7.1.jar

**Comment by fzzyhmstrs** [comment]
Trimming on modded armor requires special support, which I haven't implemented yet (or decided if I want to implement at all). If I decide to add the functionality, it will appear in the changelog of an update.
