### ISSUE TITLE
Accursed Figurine not dropping from villagers

### ISSUE THREAD

**Issue by Klauros** [fzzyhmstrs/ai#146]
I am having trouble obtaining accursed figurines.  The entry in the Glistering Tome says they drop from villagers killed by a player's hand, but I've killed several villagers, and none of them dropped one.

**Comment by fzzyhmstrs** [comment]
Its only a 10% chance. "Several" might simply not be enough to ha e gotten one

**Comment by Klauros** [comment]
Ah, I didn't realize that.  Thanks for clarifying.
