### ISSUE TITLE
Remove Spectrum's gemstone tags from your gems

### ISSUE THREAD

**Issue by Gronglegrowth** [fzzyhmstrs/ai#148]
You tag your citrine and moonstone as Spectrum's gemstones of the same type, despite this being incredibly progression breaking in the case of the latter, and generally strange. Can this tag addition be removed?

**Comment by fzzyhmstrs** [comment]
As far as I remember, I made the moonstone tag long before spectrum moonstone was even released "for production", so that tag can definitely be removed. Both citrine are basic ingredients that are widely available so I don't find the tag for citrine obtrusive or strange.

**Comment by Gronglegrowth** [comment]
,,,except that both citrines are acquired in different ways, and having both interchangeable is against Spectrum's lore and general expectations.

**Comment by fzzyhmstrs** [comment]
Then daFuqs shouldn't have a tag for it, if it matters that much

**Comment by Gronglegrowth** [comment]
There's a tag for it because it is used for more than just the shards. It includes everything pertaining to the raw gemstone - buds, "raw" geode blocks, clusters, etc.

The gemstone tags are used in progression - advancements use them to track when a player has discovered that gemstone.

**Comment by fzzyhmstrs** [comment]
I see. that can still be accomplished without a tag, which would remove the concern of "leaking" progression. 

My compromise is to make the tag, and a bunch of other random stuff "optional", with a simple kill switch of `"integration/[thing]"` in the AI config list for this purpose

**Comment by Azzyypaaras** [comment]
Hi, spectrum dev here. While integration is nice, I want to point out that those are _not_ integration tags. What you are adding items into are tags used for the mod's progression which should not be touched by anyone but pack makers.

While citrine is not as egregious as moonstone, in principle compat should not be touching those tags. AI and Spectrum are different mods with different progressions and different narratives, and gaining citrine in one does not set the proper tone nor lay down the proper knowledge for each other's progression here.

**Comment by fzzyhmstrs** [comment]
Then really you should refactor that to not be a tag, or specifically put into a `progression/` subfolder. In any case, I already have a solution for resolving it as explained above.

**Comment by fzzyhmstrs** [comment]
new versions uploaded.
