### ISSUE TITLE
what does steadfast do?

### ISSUE THREAD

**Issue by terminalmaid** [fzzyhmstrs/ai#21]
i can't find any explanation on what the enchant does lol

**Comment by terminalmaid** [comment]
i'm hosting a server and modpack and people keep asking me on what the enchantment does and i have no idea

**Comment by fzzyhmstrs** [comment]
It reduces knockback. Your players can find descriptions for all enchantments and augments in my mod by either installing [Enchantment Description](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/all?filter-status=1&filter-game-version=2020709689:7499), or by looking at the Enchantments or Augments sections of the Glistering Tome patchouli book.
