### ISSUE TITLE
Crashes on startup with carpet-fixes

### ISSUE THREAD

**Issue by dadoirie** [fzzyhmstrs/ai#22]
As the title says Amethyst Imbuement crashes on mc launch when loading it with carpet-fixed on fabric 1.18.2

![image](https://user-images.githubusercontent.com/61109153/180034293-748a941d-d375-46b7-9edc-bd85d0cabb5f.png)
those are the mods loaded

https://mclo.gs/Z966wDa
and that's the log

**Comment by fzzyhmstrs** [comment]
Unfortunately the log doesn't tell me anything. There is no error at all calling out Amethyst Imbuement. Maybe try installing [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) to try and get a better stacktrace?

**Comment by dadoirie** [comment]
My bad ... haven't checked the log after uploading it

Not Enough Crashes
https://mclo.gs/jctvvhZ
MixinTrace
https://mclo.gs/eRsIeDY
Cyanide
https://mclo.gs/tgKtt10

:)

**Comment by fzzyhmstrs** [comment]
OK, it's what I expected. A mixin conflict. Conflicting with their entity block collision fix. I'll try to see if I can come up with a
 work-around... carpet-fixes is a fairly conflict prone mod as it has a _ton_ of mixins.

**Comment by dadoirie** [comment]
btw (slightly off topic which I'd ask in a discord but since you've got no discord info) I noticed that trinket's isn't a mandatory dependency ... still required tho or?
back to topic: I've looked trough carpet-fixes options and I'd rather not exclude carpet-fixes as it has some neat fixes therefore if you'll find a work-around it'll be very appreciated

**Comment by fzzyhmstrs** [comment]
Trinkets is required for Amethyst Imbuement, so I included it in the .jar. It is _not_ mandatory for Amethyst Core because a modder using that library doesn't have to utilize the Trinkets-affected portions of the lib (AI does utilize those portions).

**Comment by fzzyhmstrs** [comment]
Issue fixed with the most recent [releases](https://www.curseforge.com/minecraft/mc-mods/amethyst-imbuement/files/3887818)
