### ISSUE TITLE
[Feature Request] EMI support

### ISSUE THREAD

**Issue by Pirogiran** [fzzyhmstrs/ai#25]
EMI is similar to REI, but have some features that REI didn't support. Can you please add support for EMI on 1.18.2?
And thanks for cool mod!

**Comment by fzzyhmstrs** [comment]
Thanks for the request! This looks like a very similar approach overall to REI, so integration shouldn't be _that_ big of a headache. I'll look into it!

**Comment by Pirogiran** [comment]
I think it'll be awesome if mod and "Crafting tree" thing will work with different tables!
Like this:
![image](https://user-images.githubusercontent.com/99805468/180771521-ac272546-211f-4901-a603-b76205637ff3.png)

So you can actually see the cost of crafting an item.

**Comment by fzzyhmstrs** [comment]
Integration with EMI is in process; currently dealing with major issues in EMI that prevent my mods blocks from functioning if EMI is installed. Intergration work will continue after that is resolved.

**Comment by Pirogiran** [comment]
Thanks for your work!

**Comment by fzzyhmstrs** [comment]
EMI support added in the newest versions! With handlers!

![image](https://user-images.githubusercontent.com/72876796/181915291-0cef3f1a-39a4-41d7-a12f-fdf89f9ae9a0.png)

![image](https://user-images.githubusercontent.com/72876796/181915298-564bd336-13f8-44a7-a4cb-949b48ece313.png)

**Comment by Pirogiran** [comment]
This is very cool! I'm definitely going to take a look now.
