### ISSUE TITLE
[Crash] Client Crashes when going into F5 while holding a Glistering Trident

### ISSUE THREAD

**Issue by pog5** [fzzyhmstrs/ai#26]
Title.

Error Log: https://pastebin.com/raw/ReRPpcwp

**Comment by fzzyhmstrs** [comment]
Unfortunately I can't replicate the crash in single- or multiplayer. Are there any other mods installed that might be conflicting? Does the crash occur consistently?

![gif_vid_blah](https://user-images.githubusercontent.com/72876796/180869241-f5e3db46-42c5-4422-9999-fb07700932be.gif)

**Comment by pog5** [comment]
Yes, I'm playing on the [SuperCharged modpack](https://modrinth.com/modpack/supercharged) on their server. It occurs every time I've tried it.

**Comment by fzzyhmstrs** [comment]
Ok I'll check that pack out and see if I can determine any conflicts, otherwise I'll have to defer the issue to the modpack creators(s), as this is some interaction issue.

BTW, do you have _Sodium_ installed? That is going to be my first check, as it conflicts with some rendering.

**Comment by pog5** [comment]
Yup, I do have Sodium installed.

**Comment by fzzyhmstrs** [comment]
Ok. Can you try it with Sodium removed and/or with [Indium](https://modrinth.com/mod/indium) installed? It would be convenient for me if that was the issue rather than having to dig thru 170+ mods for conflicts.

**Comment by pog5** [comment]
Indium already is installed, removing it or removing Sodium does not change anything for me.

**Comment by fzzyhmstrs** [comment]
Well there goes the easy solution... Something else in the modpack is causing a conflict then; I'll have to look when I get back to my computer.

**Comment by pog5** [comment]
Alright, thank you :)

**Comment by pog5** [comment]
Also, after going in F5, the game hangs for about 5 secconds and only then crashes.

**Comment by fzzyhmstrs** [comment]
I've determined the cause of this issue to be _[Pehkui](https://modrinth.com/mod/pehkui)_, and per supercharged-modpack/modpack#2 this mod will be removed tomorrow, which should clear up the crash.
