### ISSUE TITLE
mod conflict found. 

### ISSUE THREAD

**Issue by TheRanker** [fzzyhmstrs/ai#3]
seems the mod conflicsts with a mixing for spyglass improvements in the In Game Hud. mixin.  

removing the mod allows everythign to work as intended. 
using amethyst_imbuement crashes the modpack.

remove the spyglass mod indicted below.. and another error occurs

 @Redirect conflict. Skipping apoli.mixins.json:PersistentProjectileEntityMixin->@Redirect::preventDamageWhenZero(Lnet/minecraft/class_1297;Lnet/minecraft/class_1282;F)Z from mod apoli with priority 1000, already redirected by amethyst_imbuement.mixins.json:PersistentProjectileEntityMixin->@Redirect::checkHeadHunter(Lnet/minecraft/class_1297;Lnet/minecraft/class_1282;F)Z from mod amethyst_imbuement with priority 1000
[19:32:13] [main/ERROR]: Minecraft has crashed!

your mixin crashes with ... apoli 2.3.3 via origins as well..

remove Origins and spyglass improvments mod , and modpack loads up with amethyst imbuement. 

initial log - 
https://pastebin.ubuntu.com/p/Ckd9vfyGWC/

**Comment by fzzyhmstrs** [comment]
Thank you for notifying me! I'll take a look as soon as I can.

**Comment by fzzyhmstrs** [comment]
Mod conflicts with both *Apoli* and *spyglass-improvements* should be fixed in the latest mod version: [https://www.curseforge.com/minecraft/mc-mods/amethyst-imbuement/files/3755644](https://www.curseforge.com/minecraft/mc-mods/amethyst-imbuement/files/3755644)

**Comment by TheRanker** [comment]
hey bud... just wanted to update you.. your update works perfect on single player.. (havent tested server yet) . tyvm for the bug fixes. worked perfect.
