### ISSUE TITLE
[SUGGESTION] Better Combat support?

### ISSUE THREAD

**Issue by CyberSteve777** [fzzyhmstrs/ai#35]
As I see, it has wand preset (wand.json) so why do not add support for it?

**Comment by fzzyhmstrs** [comment]
I'll look into it; thanks for the suggestion!

**Comment by fzzyhmstrs** [comment]
After checking, I don't think there is anything I can actually integrate here. Better Combat upgrades attacking behavior, but the scepters are not attacking (left click), they are "using" (right click).
