### ISSUE TITLE
Imbuement doesn't appear as the first option when loading recipes

### ISSUE THREAD

**Issue by Laifsyn** [fzzyhmstrs/ai#36]
![image](https://user-images.githubusercontent.com/99366187/188792214-467818f8-a0b8-418b-bf3c-5bf5f51138ab.png)

**Comment by fzzyhmstrs** [comment]
Firstly, this is related to EMI or REI? From the pic, it seems like REI. At least with EMI, the categories are currently reverse alphabetical, and my mod starting with "A" usually means it's last. REI probably works similarly.

I have an issue open with Emi to introduce some type of category prioritization for recipes where the primary crafting method is Imbuing. In this case, the "Mage Hand" shown is not from my mod, so I'm not certain that Imbuing should come first regardless.

If this is REI I'll have to take a look at that and potentially open a similar issue.

**Comment by Laifsyn** [comment]
It's REI. I'm not sure if it only happens with custom recipes though
