### ISSUE TITLE
Crash beta version on modpack

### ISSUE THREAD

**Issue by Silverbolt666** [fzzyhmstrs/ai#41]
[crash-2022-09-10_15.15.50-client.txt](https://github.com/fzzyhmstrs/ai/files/9540541/crash-2022-09-10_15.15.50-client.txt)

The modpack doesn't load with the latest version of the mod installed.

**Comment by fzzyhmstrs** [comment]
Try removing amethyst-core 0.2.3 from your modlist. the new version is embedded with an updated version, but seems the modpack is picking the lower version for some reason

**Comment by Silverbolt666** [comment]
Solved, didn't notice it had Amethyst Core installed, I had deleted it several times already. Thanks for the help
