### ISSUE TITLE
Duping Issue in Multiplayer

### ISSUE THREAD

**Issue by ExcaliburRockin** [fzzyhmstrs/ai#43]
Crafting an item in an imbuement table while your friend repeatedly changes or removes the middle item for crafting can create a 2nd item.

**Comment by fzzyhmstrs** [comment]
Wow, that's quite the fun bug. What is an example recipe you've noticed this happening on? Are both items the "result item" or do you end up with one pre-craft middle item and one crafted?

I might simply make it so other players either can't look at a table that's in use or can't interact with the imbuing table inventory if another player opened it first.

**Comment by ExcaliburRockin** [comment]
You dupe the ingredient or the random item, the crafted item comes out normally. The recipe we noticed this on was with crystaline hearts
