### ISSUE TITLE
Infinite Absorption Hearts

### ISSUE THREAD

**Issue by ExcaliburRockin** [fzzyhmstrs/ai#45]
Wearing any trinket with an absorption bonus, getting absorption hearts from another source like a golden apple, then taking on and off the trinket will duplicate the absorption heart bonus, there seems to be no ceiling.

**Comment by fzzyhmstrs** [comment]
Did you mean to close this? I've actually been trying to replicate this issue for a while, and the Golden heart tidbit I think is pointing me towards the solution

**Comment by ExcaliburRockin** [comment]
I did not mean to close it, The issue is seemingly caused by mods with permanent absorption hearts. Normally taking off the amulet or other trinket clears the effect but when another source of absorption stays on it keeps replicating those hearts.

**Comment by ExcaliburRockin** [comment]
I tried running the mod by itself and the issue does not happen, but it does with any mod I try that offers non-decaying absorption hearts. 

Ex. Warden Tools mod, Simply Swords mod.

**Comment by fzzyhmstrs** [comment]
I've tested it with golden apples and they were enough to cause it for me. Also enough info for me to have a fix, which will be pushed out soon.

**Comment by ExcaliburRockin** [comment]
Thank you!
