### ISSUE TITLE
[SUGGESTION] Compat for mods that add some of the same gemstones as you

### ISSUE THREAD

**Issue by Sunconure11** [fzzyhmstrs/ai#49]
An example would be Tech Reborn, as it has a few variants of garnet.

**Comment by fzzyhmstrs** [comment]
I've had this thought before, and am certainly open to the idea. I haven't gotten around to figuring out exactly how I'd handle it at the end of the day. 

One issue is that certain gems are much easier to obtain in other mods than they are assumed to be in AI. Citrine from Spectrum, for example, is found all over in geodes, while  it can only be obtained naturally in the Nether in AI. These gems also don't have common/fabric tags at the moment, so the implementation would be a bit tricky.

One direction I've considered taking is an "Amethyst Additions" style of addon mod that adds brand new recipes aimed at integrating other gem mods, especially Spectrum, which is a similarly themed mod overall.
