### ISSUE TITLE
Tom's Simple storage mod Incompatibility 

### ISSUE THREAD

**Issue by Kuggle01** [fzzyhmstrs/ai#50]
For some reasson, any books of lore put into a storage network from Tom's simple Storage mod https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric cannot be taken out once they are put in

**Comment by fzzyhmstrs** [comment]
Thanks for the report. Ill try to look into it, but seems maybe like an issue on their end

**Comment by fzzyhmstrs** [comment]
Cannot replicate in 1.19.2.
