### ISSUE TITLE
'Create Lava/Water/Sponge' on multiplayer server doesn't apply cooldown and causes a glitched timed out bug

### ISSUE THREAD

**Issue by LadyPari** [fzzyhmstrs/ai#51]
Modpack: DarkRPG version 4.4.8
World Type: Multiplayer

Like the title says, when those spells are used their internal cooldowns (Which normally show on the scepter) does not proc. This **ONLY** happens in Multiplayer servers as far as I'm aware. I've gone to the liberty of trying in a Singleplayer world where it works fine. So I am unsure if it's the multiplayer world in specific or something else going wrong. I was simply told by Nereidalbel from the DarkRPG server to let you know of this through Github. 

From what I can see through Task Manager when Sparrow asked me to test, when the spell(s) in question are used in successive casting and their cooldown either becomes 0 or 3-5s instead of the full 10, it causes the Ethernet graphs to completely cap out and go crazy for some reason, besides that I have no clue. Shortly after though you'll notice (if you have any refreshing buffs like Immunity) that your buffs start ticking down and no longer refresh which solidifies your game either having a seizure for a brief moment OR that you will be evicted momentarily. 

For the DarkRPG server in particular you have a 33% chance of being timed out and glitched inside their server as a result when the above is done with any of the 'Create X' spells that ignore the cooldown. 

I hope this helps in someway somehow!

**Comment by fzzyhmstrs** [comment]
Thank you for the detailed report! I will look into it

**Comment by LadyPari** [comment]
Separate issue from it but less talked about as it happens far less but 'Create Water' apparently has a chance to boot you regardless of usage inside the server. My partner used it once to get down a hole and got instantly timed out/glitched in.

**Comment by fzzyhmstrs** [comment]
I'll try to replicate on my test server. Without a server log it's tough to say what exactly is happening. I am already working on an alternate implementation of the spells inner workings, so that may be moot. But still, I'm currently waving a stick around in the dark trying to solve the weird network-going-crazy issue. 

The cooldown issue I think I have under control. Hopefully that translates into solving the other issue too.

**Comment by fzzyhmstrs** [comment]
These issues should be resolved in the newest versions
