### ISSUE TITLE
imbuing table does not benefit from better enchantment boosting

### ISSUE THREAD

**Issue by stage-owl** [fzzyhmstrs/ai#52]
With only Amethyst Imbuement and Better Enchantment Boosting installed, the Imbuing Station does not benefit from bookshelves outside of the typical 5x5 ring centered on the station. This seems unintentional given the config option in altars_v2.cfg

`"imbuingTableMatchBetterEnchantmentBoostingBehavior": true,`

Glyph particles generate and move towards the station as expected, but the enchanting level does not change.

**Comment by fzzyhmstrs** [comment]
The functionality for BetterEnchantmentBoosting compatibility isn't fully implemented yet. The config option is basically a placeholder at the moment as I work on integrations.

**Comment by stage-owl** [comment]
Ah alright, thank you for clarifying. Looking forward to seeing the mod expand :)!
