### ISSUE TITLE
Book of Lore - Totem of Fury

### ISSUE THREAD

**Issue by LadyPari** [fzzyhmstrs/ai#53]
DarkRPG Multiplayer ver. 4.5.8

![image](https://user-images.githubusercontent.com/93747436/198938768-f50d5b7a-c5d4-4be5-87c1-3dd9dd100064.png)

The imbuement recipe (Tier 2 Fury) doesn't work. When all items are put in, nothing pops up at all. Have tried with different scepters to the same result. The recipe in question within the table:

![image](https://user-images.githubusercontent.com/93747436/198939008-9b2ac58a-31c9-4a95-86e9-0c3d2e7e19a3.png)

**Comment by fzzyhmstrs** [comment]
That's not working because Summon Totem of Fury uses a _Lethal Gem_ as it's top left gem, not a garnet. If you use the lore book, it should show you the recipe. I should add a section to the guide book for the totem spells. They all use special gems, not the template gem.
