### ISSUE TITLE
Bug(?) for Force Field

### ISSUE THREAD

**Issue by LadyPari** [fzzyhmstrs/ai#54]
There are 2 books for the same spell but categorized in two different categories. It exists in both Wit and Grace lore books but is learned by Wit methods:
![image](https://user-images.githubusercontent.com/93747436/199648635-439fcaa1-5570-42f9-9690-b2c70225cd78.png)
![image](https://user-images.githubusercontent.com/93747436/199648662-970e2253-cfe6-4bb6-b34d-e53f9385211c.png)

Not sure which it was really intended for but both of them stack separately with their respective bookmarkers (Blue or Green) so we have collectively 9 total but 6 in the wit stack and 3 in the grace stack.

DarkRPG ver. 4.6.0.

**Comment by fzzyhmstrs** [comment]
I changed Forcefield to a wit spell in the latest update, which didn't update the nbt flag in existing lore books that determines their bookmark color. As such there may be some books floating around with the old tag that are just an artifact of the spell tweaking.
