### ISSUE TITLE
Disenchanting table can strip enchants off certain items without removing the enchant from the item

### ISSUE THREAD

**Issue by Veracis-Eclise** [fzzyhmstrs/ai#58]
![image](https://user-images.githubusercontent.com/118526661/202681830-8dfe0260-974e-4a38-a936-e1c46c8199d4.png)

Issue discovered during interaction between MC Dungeon Weapons and Amethyst Imbuement. (Issue is most likely prevalent with MC Dungeon Armors as well)

As referenced in the image, when the disenchanting table attempts to remove enchants from MC Dungeon weapons that have inherent enchants such as the The End (has Void Strike 1), the disenchantment succeeds however the enchant remains on the weapon, allowing for continuous disenchanting of that specific enchant. This is only possible when the item itself is enchanted with different enchants (Via enchanting table or anvil) or with a higher level of its own base enchant. As per the image, it seems the inherent enchants to the weapon are not intended to be "discoverable"

- Issue was discovered and replicated on the DarkRPG Modpack. A vanilla world with both mods can also reproduce the issue.

**Comment by fzzyhmstrs** [comment]
The source of this interaction has been identified as `getEnchantments` from `ItemStack`. I will need to implement a workaround helper method to avoid "ghost enchants", or use an alternative vanilla method for getting the enchantment list.

@Veracis-Eclise this is mostly a note to myself :)

**Comment by fzzyhmstrs** [comment]
This has been resolved in the latest updates
