### ISSUE TITLE
Way to turn off starting glistering tome

### ISSUE THREAD

**Issue by Hyomoto** [fzzyhmstrs/ai#60]
I dug through the configs and I don't see any simple way to remove the starting tome.  Either I'm overlooking it or this is a weird oversight.  For clarity, on a sever this isn't the primary mod and while it's nice to have *available*, the book is craftable after all, that doesn't mean that players should start with such an item.  It adds to the sense of progression to have to craft the tome rather than just being handed one.

**Comment by fzzyhmstrs** [comment]
You are right, there isn't currently a simple way to remove that functionality with configs. Currently that is actually handled with a hidden advancement.

I can look into a way to add my own advancement criterion that interfaces with my configs. I certainly understand various reasons to not want it to be auto-given. I also have had requests specifically to have it given on start, so in the end there will have to be some sort of switch.

**Comment by fzzyhmstrs** [comment]
This should be possible now with the recent releases of AI. I've added the option to turn this off in the now-"Items" config
