### ISSUE TITLE
Draconic Vision outline is always white no matter the ore

### ISSUE THREAD

**Issue by faeldray** [fzzyhmstrs/ai#61]
Issue: The outline around ores using Draconic Vision is always white no matter the circumstance, which makes it impossible to know what kind of ore is being highlighted without actually seeing it.

Loader: Quilt 0.18.1-beta.18

Mods:
amethyst_imbuement-1.18.2-38.jar
architectury-4.10.86-fabric.jar
cloth-config-6.3.81-fabric.jar
fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0_mc-1.18.2.jar
RoughlyEnoughItems-8.3.573.jar

![2022-11-27_12 42 51](https://user-images.githubusercontent.com/967709/204153766-14a31f4a-e14c-425d-b023-53b76923a614.png)

**Comment by fzzyhmstrs** [comment]
This is unfortunately expected behavior at the moment. I had to take out the library that was coloring the ores due to issues it was creating on servers. I hope to have the colors back at some point in the future!

**Comment by faeldray** [comment]
Ah that's too bad but also good to know. I don't know if this'll help but the [Spelunker mod](https://www.curseforge.com/minecraft/mc-mods/spelunker) does a very similar thing (I don't know if they use entities though) and has coloured outlines around the ores.
