### ISSUE TITLE
question doe this mod add higher levels of vanilla enchantmetns?

### ISSUE THREAD

**Issue by dpe0** [fzzyhmstrs/ai#63]
trying to find what mod did that in my game
![sasaassaasas](https://user-images.githubusercontent.com/76593873/206906273-ccda3b4d-856f-4715-8f6d-324740ecfd30.png)

**Comment by fzzyhmstrs** [comment]
Cute hamster pic :). Yes, AI increases the max level of some enchantments

**Comment by dpe0** [comment]
> Cute hamster pic :). Yes, AI increases the max level of some enchantments

is it possible to disable that?

**Comment by fzzyhmstrs** [comment]
Its not currently possible to disable that feature.
