### ISSUE TITLE
Items in imbuing table get destroyed upon breaking the imbuing table

### ISSUE THREAD

**Issue by david-frederick-batt** [fzzyhmstrs/ai#69]
Items which get put into the imbuing table get lost when the imbuing table is broken. The mod is being used in conjunction with Easy Magic.

**Comment by fzzyhmstrs** [comment]
This issue was just pointed out to me elsewhere, it will be patched in the next update!

**Comment by fzzyhmstrs** [comment]
Fixed in the latest versions
