### ISSUE TITLE
Modifiers can't be upgraded with the progress of scepter.

### ISSUE THREAD

**Issue by IwasConfused** [fzzyhmstrs/ai#72]
When upgrade Corrupted Scepter to Lethality, the modifier Dangerous and Pact of Danger did not upgrade to Lethal and Pact of Lethality, same on other modifiers (Protective, Champion of the Meek etc. ).
![2](https://user-images.githubusercontent.com/70762136/217825488-5b9bcd64-ef70-4ed5-a81f-71b36bbd80b8.png)
![3](https://user-images.githubusercontent.com/70762136/217825498-815610b4-2d74-40ec-9cb4-a5ac0411cfb5.png)

**Comment by fzzyhmstrs** [comment]
Are you on a server? It may be a visual bug if so, where the client hasn't properly realized that the modifiers have changed. I'll take a look either way, and if you are in single player I'll definitely have to take a look

**Comment by fzzyhmstrs** [comment]
I may have determined a potential source of the issue, but unfortunately don't be able to test my theory for a few hours.

**Comment by fzzyhmstrs** [comment]
Fixed in latest release
