### ISSUE TITLE
Magic missile XP duplication

### ISSUE THREAD

**Issue by IwasConfused** [fzzyhmstrs/ai#73]
Spell "Magic Missile" can be removed by grindstone and get XPs, but you can get the spell again by crouching and scrolling. Repeating this step will cause XP duplication.

**Comment by fzzyhmstrs** [comment]
AH shoot this was brought up earlier but I totally forgot. Thanks for posting the issue!

**Comment by fzzyhmstrs** [comment]
Fixed in latest release. Scepter does not gain a new magic missile and active spell becomes "None"
