### ISSUE TITLE
Invalid Player Data error when creating a new world

### ISSUE THREAD

**Issue by Sunconure11** [fzzyhmstrs/ai#78]
https://gist.github.com/Sunconure11/841a32659a5d7b04c68cd62a891580e6

**Comment by fzzyhmstrs** [comment]
Have you opened an issue with "Effective Regalia"? There is a mixin handler from them above mine in the stack trace:

![image](https://user-images.githubusercontent.com/72876796/227992496-93f2613b-fdac-405c-b91c-d60701752f0f.png)

**Comment by fzzyhmstrs** [comment]
Closing for now based on DakotaPride's comments in the referenced issues. If the issue persists after 0.3 of Effective Regalia, this can be reopened
