### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by variety754** [fzzyhmstrs/ai#79]
https://mclo.gs/g5CGsfP

**Comment by variety754** [comment]
crash happens only when Cursery and Amethyst Core or Amethyst Imbuement installed

**Comment by fzzyhmstrs** [comment]
There is no crash logged in the provided link, so I have nothing to diagnose.

**Comment by variety754** [comment]
That must be something with the logs. I checked all logs I got from this crash and not a single one contains the problem. I guess you'll need to replicate this issue yourself by installing Cursery and Amethyst Imbuement together. Sorry.

**Comment by fzzyhmstrs** [comment]
I still can't replicate it in my test pack. I launched into the game just fine with the latest versions of AI and Cursery
![image](https://user-images.githubusercontent.com/72876796/233849089-57afac49-b9fc-4749-b607-53ccb2d5394a.png)

**Comment by variety754** [comment]
I guess I need to somehow make logs work properly. I'll try some things, but that will take a few days. Me and my family are moving, no time for Minecraft.

**Comment by variety754** [comment]
Wait, can I somehow export modpack where I'm experiencing an issue? So that if I will not be able to fix logs, you will have my environment

**Comment by fzzyhmstrs** [comment]
If you are using the Curseforge Launcher you should be able to export it as a modpack. I'm not familiar with how to do it with other launchers.
![image](https://user-images.githubusercontent.com/72876796/233861346-49cb3663-43af-42b7-8b01-fdce08b50256.png)

**Comment by variety754** [comment]
Yes, I'm using CurseForge launcher. I will try my best to find time to send it to you tomorrow.

**Comment by variety754** [comment]
[2023-04-30-4.log](https://github.com/fzzyhmstrs/ai/files/11360543/2023-04-30-4.log)
Here is crash log. But latest logs are still broken for some reason

**Comment by fzzyhmstrs** [comment]
Closing this because it's stale, and none of the logs actually are showing an issue, and I've never been able to replicate.
