### ISSUE TITLE
Intinial world load crash

### ISSUE THREAD

**Issue by Kuggle01** [fzzyhmstrs/ai#8]
The game is crashing whenever I load a world for the first time only, any time after that it seems to be fine, I think it may have something to do with amethyst imbuement https://paste.ee/p/ipbyb

**Comment by fzzyhmstrs** [comment]
Strange. Something is trying to read an imbuing recipe before my item registry is loaded, at least client-side. I don't think it's *caused* by Amethyst Imbuement per se, as I can load my test server and/or client without the No Such Element exception being thrown.

Seems like something may be adding my recipes to the vanilla recipe book? I believe the `class_366` that tried to call my recipe is the RecipeToast class, the class responsible for making the "New recipes unlocked!" toast appear on screen. Do you know if any mod like that is loaded in the modpack? I don't know what recipes it would be trying to show as unlocked as soon as you join a world....

Do you know what recipes it's showing as available to you?

I believe I have a workaround, but it may end up showing incorrect recipes in the toast (just blank results). Please let me know if the below test jar lets you join a world without crashing:

**The .jar is inside the .zip**
[amethyst_imbuement-1.18.2-07-Kuggle01-test.zip](https://github.com/fzzyhmstrs/ai/files/8578447/amethyst_imbuement-1.18.2-07-Kuggle01-test.zip)

**Comment by Sunconure11** [comment]
Getting the same error.

https://pastebin.com/TH1rAAjv

**Comment by fzzyhmstrs** [comment]
> Getting the same error.
> 
> https://pastebin.com/TH1rAAjv

@Sunconure11 the test .jar 1.18.2-07-Kuggle01-test above should also fix it for you. Please let me know if it does. 

Do you know if you have a mod installed that modifies the vanilla recipe book? Or what recipe(s) the Toast is trying to display?

**Comment by Sunconure11** [comment]
I'll test it in a bit. I'm checking another mod for a bug of it's own.

**Comment by Kuggle01** [comment]
Origins maybe? That does have a pop-up at the begining of the world to select an origin

**Comment by fzzyhmstrs** [comment]
I'm closing this as I believe the crashing is fixed in the newest releases. I still don't know what is actually precipitating the recipe read, but it should no longer crash at least. If you still are finding the same issue with the newest versions, feel free to reopen.
