### ISSUE TITLE
[Suggestion] Config option to not remove Undying enchant from Totem of Amethyst

### ISSUE THREAD

**Issue by grundyboy34** [fzzyhmstrs/ai#80]
I'd really love to have a config option so that Undying doesn't get removed from the totem when triggered (but still breaks it so it needs repair). Or better yet, an option to disable augment burnout in general. The enchant is insanely expensive, to the point it's actually easier to just farm some raids for the vanilla totem of undying instead.

Another nice to have, would be a config option or something so that Soulbinding uses some of the totem's durability when triggered.

**Comment by fzzyhmstrs** [comment]
you can make undying reusable with the current config by altering the totem durability slightly. If you make it, say, 380, Undying won't burn out but will come very close to it. 

I will consider both of your other suggestions as well. I understand where you are coming from regarding augment cost, and soulbinding probably should have a cost associated with it.

**Comment by fzzyhmstrs** [comment]
This has been implemented in recent versions
