### ISSUE TITLE
StackOverflow crash on opening Book of Mythos

### ISSUE THREAD

**Issue by variety754** [fzzyhmstrs/ai#82]
Crash log I'll send you containing a not enough memory crash produced by the same error. For some reason stackoverflow crash logs are not creating and latest.logs are still broken. 
[2023-05-03-3.log](https://github.com/fzzyhmstrs/ai/files/11378583/2023-05-03-3.log)
Why everything is so broken with Minecraft... Someday I will go insane trying to fix all of this

**Comment by fzzyhmstrs** [comment]
The mod "screenscale" appears to be causing this headache.

**Comment by variety754** [comment]
Is it fixable? Or should I open issue on screenscale mod page?
