### ISSUE TITLE
[Suggestion] Make actual animation for Heartstone

### ISSUE THREAD

**Issue by variety754** [fzzyhmstrs/ai#84]
For the heartstone there is a description "pulses gently in your hand". It would've been really cool if there was animation when you see this item in inventory or in your hand
![image](https://user-images.githubusercontent.com/124847943/236091336-11407a70-db40-41e7-8a44-d44facdfade1.png)

**Comment by fzzyhmstrs** [comment]
This is certainly something I can consider when I have some time.
