### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kuggle01** [fzzyhmstrs/ai#9]
https://paste.ee/p/btQWt I'm not really sure why or how, but I know it HAS to be this mod because the game always crashes when I hover my mouse over certain spell books. This leaves my world completely bricked. I started this world with an older version of the mod, and I updated to a newer version while keeping the old world, IDK if that has anything to do with it

**Comment by fzzyhmstrs** [comment]
Thank you for the report. This looks like an error introduced when I updated how some of my text generates. Fixed in the newest releases on curseforge.
