### ISSUE TITLE
Soul Missile On Lethality Scepter uses Magic Missile

### ISSUE THREAD

**Issue by Creater2036** [fzzyhmstrs/ai#94]
Hello! Been loving these updates and all the new stuff in the mod, so thank you :) One issue I've encountered though is that for some reason the Lethality Scepter I've build from Route of Dangerous Corruption which should come with soul missile uses magic missile instead for some reason but still levels fury up. Could you help with this? Thank you!

**Comment by fzzyhmstrs** [comment]
Are you sure it isn't in fact soul missile? It looks and sounds identical to magic missile except for the trail of particles it leaves is the 'soul' particles from soul speed, not the star particles.

**Comment by fzzyhmstrs** [comment]
Closing stale issue due to no response
